### ISSUE TITLE
靠右固定后，显示隐藏窗口出现位置不固定

### ISSUE THREAD

**Issue by kwosmiles** [heyManNice/myCopilot#1]
窗口一个浏览器，靠右固定后，显示隐藏窗口出现位置不固定，有时候为靠右，有时候为悬浮框，有时候贴着浏览器靠右，但是右边还有位置，有时候消失不见
![屏幕截图 2024-11-21 130149](https://github.com/user-attachments/assets/ff51cda4-87ca-466b-92ea-f8cc62d4a56a)
![屏幕截图 2024-11-21 130219](https://github.com/user-attachments/assets/28ac524c-3ba8-4098-9b18-f9bd243a7627)

**Comment by kwosmiles** [comment]
按alt+c悬浮窗口时，在有些应用下，窗口不会显示到最顶层

**Comment by heyManNice** [comment]
- 我无法复现你的问题，但我已经依靠推测修改代码。修复该问题的二进制程序已经发布在latest release啦！
- 下载`fix_issue1_winx64_241121Beta.exe`并复制到与`Copilot.exe`相同的目录下（无需重命名）即可在不丢失用户数据情况下运行`fix_issue1_winx64_241121Beta.exe`。（注意：在运行之前请先退出`Copilot.exe`）
- 测试完后，无论是否成功修复，请告诉我程序的运行效果，这将有助于我们了解并将代码汇入主分支。

**Comment by kwosmiles** [comment]
windows版本
Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎10/‎11
操作系统版本	26100.2314
体验	Windows Feature Experience Pack 1000.26100.32.0
使用fix.exe测试，无效果。录屏如下
https://ali-meet-1329442433.cos.ap-beijing.myqcloud.com/recording/record_2024-11-22_15-22-32.mp4

**Comment by heyManNice** [comment]
你确定你已经通过托盘右键菜单退出了`Copilot.exe`才运行`fix_issue1_winx64_241121Beta.exe`的吗？如果`fix_issue1_winx64_241121Beta.exe`发现`Copilot.exe`没有退出，它将不会运行

**Comment by kwosmiles** [comment]
> 你确定你已经通过托盘右键菜单退出了`Copilot.exe`才运行`fix_issue1_winx64_241121Beta.exe`的吗？如果`fix_issue1_winx64_241121Beta.exe`发现`Copilot.exe`没有退出，它将不会运行

是的，如果你需要我可以加你演示给你看

**Comment by heyManNice** [comment]
> > 你确定你已经通过托盘右键菜单退出了才运行的吗？如果发现没有退出，它将不会运行`Copilot.exe``fix_issue1_winx64_241121Beta.exe``fix_issue1_winx64_241121Beta.exe``Copilot.exe`
> 
> 是的，如果你需要我可以加你演示给你看

不用了，我只是想确认一下。这确实很奇怪，容我仔细研究研究，如果后续有进展我会通知你

**Comment by kwosmiles** [comment]
fixed：https://github.com/kwosmiles/myCopilot/commit/9b83208bcfa378a753ec84280d928d632e799eaf
