### ISSUE TITLE
目前靠边固定功能不支持多显示器

### ISSUE THREAD

**Issue by jidh1209** [heyManNice/myCopilot#2]
Environment: 两个或更多显示器
Step:
1. 将“my copilot”移动到第二显示器
2. 点击任务栏靠右固定或靠左固定
3. my copilot会自动固定到主显示器中

**Comment by heyManNice** [comment]
已更新到latest release啦，赶快试试吧！确定没有问题之后请关闭这个issue。

**Comment by jidh1209** [comment]
问题已解决，谢谢。
