### ISSUE TITLE
之前可以打开，现在打不开了

### ISSUE THREAD

**Issue by maple323** [heyManNice/myCopilot#3]
不知道什么原因

**Comment by maple323** [comment]
edge的网页版可以访问

**Comment by heyManNice** [comment]
请描述一下具体的现象

**Comment by maple323** [comment]
![10747170441582250508](https://github.com/user-attachments/assets/b0c8c5f8-7fd9-40e4-abfd-23cfc77215a8)
打开会显示这个，现在又可以打开了。

**Comment by heyManNice** [comment]
- 设置全局快捷键失效可能是你安装了某些软件占用了alt+c快捷键，这会导致myCopilot无法使用快捷键，但不影响运行。
- 通过在微软官方文档查询错误码1409得出错误原因是快捷键已被注册
- 你可以使用第三方工具检测一下有哪些程序在使用快捷键。
- 如果你想更换myCopilot的快捷键的话可以下载源码，到./include/config.hpp修改配置文件，重新编译即可
- 如果问题已经解决就可以把这个issue关闭了。

**Comment by maple323** [comment]
好的，现在可以了
